# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

In [2]:
import numpy as np

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [3]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:    ", today)
print("Tomorrow: ", tomorrow)

Yesterday: 2025-09-12
Today:     2025-09-13
Tomorrow:  2025-09-14


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [4]:
july_dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(july_dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [5]:
A = np.arange(1, 6, dtype=float)  
B = np.arange(6, 11, dtype=float) 

# Step 1: A += B   (A now holds A+B)
np.add(A, B, out=A)

# Step 2: A *= (-A/2)   (in place multiply)
np.multiply(A, -A/2, out=A)

print(A)

[ -24.5  -40.5  -60.5  -84.5 -112.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [6]:
Z = np.random.uniform(0, 10, 5)   # 5 random floats in [0,10)
print("Original:", Z)

# Method 1: np.floor
print("Floor:   ", np.floor(Z))

# Method 2: astype(int)
print("astype:  ", Z.astype(int))

# Method 3: np.trunc (truncate toward zero)
print("Trunc:   ", np.trunc(Z))

# Method 4: np.ceil(Z) - 1  (valid since Z > 0 and not integer already)
print("Ceil-1:  ", np.ceil(Z) - 1)

Original: [5.25639746 4.1534041  6.14892029 9.26804529 2.6566457 ]
Floor:    [5. 4. 6. 9. 2.]
astype:   [5 4 6 9 2]
Trunc:    [5. 4. 6. 9. 2.]
Ceil-1:   [5. 4. 6. 9. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [7]:
w = np.zeros((5,5)) + np.arange(5)
print(w)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [9]:
def gen():
    for i in range(10):
        yield i   # produces numbers 0 → 9 one by one

# Build array from generator
arr = np.fromiter(gen(), dtype=int)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [11]:
p = np.linspace(0, 1, 12)[1:-1]  # create 12 points and drop first & last
print(p)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
u = np.random.rand(10)   

print("Before sort:", u)

# Sorting
u_sorted = np.sort(u)
print("After sort: ", u_sorted)

Before sort: [0.19652255 0.7280699  0.97344836 0.25195902 0.01050815 0.84126662
 0.90067924 0.69388231 0.29490214 0.81480466]
After sort:  [0.01050815 0.19652255 0.25195902 0.29490214 0.69388231 0.7280699
 0.81480466 0.84126662 0.90067924 0.97344836]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [13]:
a = np.array([1, 2, 3, 4, 5])
result = a.sum()  
print(result)

15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [14]:
A = np.random.randint(0, 5, (3,3))
B = np.random.randint(0, 5, (3,3))

print("A:\n", A)
print("B:\n", B)

# 1. Element-wise comparison
print("Element-wise:\n", A == B)

# 2. Check if all elements are equal
print("Arrays equal?:", np.array_equal(A, B))

# 3. For floating-point arrays (with tolerance)
print("Arrays close?:", np.allclose(A, B))

A:
 [[4 3 2]
 [1 1 2]
 [2 4 3]]
B:
 [[2 1 3]
 [0 2 1]
 [1 2 2]]
Element-wise:
 [[False False False]
 [False False False]
 [False False False]]
Arrays equal?: False
Arrays close?: False


#### 43. Make an array immutable (read-only) (★★☆)

In [15]:

# Create a normal array
a = np.arange(10)
print("Before:", a)

# Make it read-only
a.flags.writeable = False

# Try modifying it (it will raise an error)
try:
    a[0] = 99
except ValueError as e:
    print("Error:", e)

Before: [0 1 2 3 4 5 6 7 8 9]
Error: assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [16]:
# Create a random 10x2 matrix for (x, y)
Z = np.random.random((10, 2)) * 10   # random values scaled for clarity

# Separate x and y
x = Z[:, 0]
y = Z[:, 1]

# Convert to polar coordinates
r = np.sqrt(x**2 + y**2)        # radius
theta = np.arctan2(y, x)        # angle in radians

# Combine into polar coordinates
polar = np.column_stack((r, theta))

print("Cartesian (x, y):\n", Z)
print("\nPolar (r, θ):\n", polar)

Cartesian (x, y):
 [[5.96906838 9.64057175]
 [9.05532748 8.48093963]
 [1.69442428 7.9412875 ]
 [0.08451952 1.79370502]
 [4.34610377 8.28744131]
 [1.67912171 2.20182639]
 [8.19111274 8.30667243]
 [7.9624237  0.3210788 ]
 [1.35986461 1.71816009]
 [1.48642577 8.0787129 ]]

Polar (r, θ):
 [[11.33888888  1.01640669]
 [12.40666325  0.75265559]
 [ 8.12004438  1.36057966]
 [ 1.7956952   1.52371107]
 [ 9.35790048  1.08780375]
 [ 2.76902314  0.91927731]
 [11.66598194  0.79240261]
 [ 7.9688947   0.04030242]
 [ 2.19118822  0.90128099]
 [ 8.21432065  1.38883851]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [17]:

Z = np.random.random(10)
print(Z)

# Find the index of the maximum value
max_idx = Z.argmax()

# Replace maximum value with 0
Z[max_idx] = 0
print("\nModified vector:\n", Z)

[0.43174818 0.14114726 0.61183267 0.88156397 0.67255543 0.01431094
 0.20252118 0.34442193 0.56433435 0.00817633]

Modified vector:
 [0.43174818 0.14114726 0.61183267 0.         0.67255543 0.01431094
 0.20252118 0.34442193 0.56433435 0.00817633]
