# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 61. Find the nearest value from a given value in an array (★★☆)

In [4]:
t= np.random.uniform(0, 100, 10)   # random values between 0 and 100
print("Array:\n", t)

# Given value
num = 50

# Find index of nearest value
idx = (np.abs(t- num)).argmin()

print(f"\nGiven value: {num}")
print(f"Nearest value in array: {t[idx]}")


Array:
 [37.89931401 13.4648098  33.23136415 17.67369911 29.77762094 48.11890742
 34.30547777 72.73844952 69.53077952 44.25858353]

Given value: 50
Nearest value in array: 48.118907422944424


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:

A = np.arange(3).reshape(1, 3)   
B = np.arange(3).reshape(3, 1)   

print("A:\n", A)
print("B:\n", B)

# Use nditer with broadcasting
it = np.nditer([A, B, None])
for x, y, z in it:
    z[...] = x + y   # compute sum

# Reshape result to broadcasted shape
result = it.operands[2]
print("\nResult (A+B):\n", result)

A:
 [[0 1 2]]
B:
 [[0]
 [1]
 [2]]

Result (A+B):
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [6]:
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name="unnamed"):
        # Convert input to ndarray, then view as NamedArray
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        # This makes sure 'name' is preserved during slicing/copying
        if obj is None: return
        self.name = getattr(obj, 'name', "unnamed")

# Example usage
a = NamedArray([1, 2, 3, 4], name="MyArray")
print(a)
print("Name:", a.name)

# Slice example
b = a[1:3]
print("\nSliced:", b)
print("Sliced Name:", b.name)

[1 2 3 4]
Name: MyArray

Sliced: [2 3]
Sliced Name: MyArray


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
Z = np.zeros(10, dtype=int)
I = [2, 3, 3, 5]

np.add.at(Z, I, 1)   
print(Z)

[0 0 1 2 0 1 0 0 0 0]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [26]:
X = np.array([1, 2, 3, 4, 5])

# Indices where values should go
I = np.array([0, 1, 1, 2, 2])

# Target array (size must cover max index)
F = np.zeros(3, dtype=int)

# Accumulate
np.add.at(F, I, X)

print(F)

[1 5 9]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [27]:
# Example: random image (w=4, h=4, 3 channels, dtype=uint8)
w, h = 4, 4
image = np.random.randint(0, 256, size=(w, h, 3), dtype=np.uint8)

# Reshape to list of pixels
pixels = image.reshape(-1, 3)

# Find unique rows (unique colors)
unique_colors = np.unique(pixels, axis=0)

# Number of unique colors
num_colors = len(unique_colors)

print("Unique colors:\n", unique_colors)
print("Number of unique colors:", num_colors)

Unique colors:
 [[  8 205 243]
 [ 12 203 173]
 [ 29   3  62]
 [ 29 185 222]
 [ 96  62 121]
 [130  35 118]
 [133 147 194]
 [134 250  99]
 [192   9 190]
 [199  79   7]
 [204 177 124]
 [208 199 147]
 [216 167 149]
 [222  82 187]
 [238  35 175]
 [254  71  53]]
Number of unique colors: 16


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
Z = np.random.rand(2, 3, 4, 5) 

# Sum over the last two axes
result = Z.sum(axis=(-2, -1))

print("Shape before:", Z.shape)
print("Shape after :", result.shape)

Shape before: (2, 3, 4, 5)
Shape after : (2, 3)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [29]:
#  Data
D = np.array([10, 20, 30, 40, 50, 60])
S = np.array([0, 1, 0, 1, 2, 2])   # subset labels

# Step 1: get sums per group
sums = np.bincount(S, weights=D)

# Step 2: get counts per group
counts = np.bincount(S)

# Step 3: compute means
means = sums / counts

print("Sums :", sums)
print("Counts:", counts)
print("Means:", means)

Sums : [ 40.  60. 110.]
Counts: [2 2 2]
Means: [20. 30. 55.]


#### 69. How to get the diagonal of a dot product? (★★★)

In [30]:
A = np.random.rand(4, 5)
B = np.random.rand(5, 4)

diag = np.diag(np.dot(A, B))
print(diag)

[1.75551286 1.42990925 1.71998157 0.39345049]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [31]:
Z = np.array([1, 2, 3, 4, 5])
k = 3  # number of zeros to insert

# Create new array filled with zeros
out = np.zeros(len(Z) * (k + 1), dtype=Z.dtype)

# Fill every (k+1)-th position with Z
out[::k+1] = Z

print(out)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [32]:
A = np.random.rand(5, 5, 3)
B = np.random.rand(5, 5)

# Expand B to match A’s shape
C = A * B[:, :, None]    #B[:, :, None] → reshapes B from (5,5) → (5,5,1).

print("A shape:", A.shape)
print("B shape:", B.shape)
print("C shape:", C.shape)

A shape: (5, 5, 3)
B shape: (5, 5)
C shape: (5, 5, 3)


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
A = np.arange(12).reshape(4, 3)
print("Original array:\n", A)

# swap row 1 and row 3 (0-based indexing)
i, j = 1, 3
A[[i, j]] = A[[j, i]]

print("\nAfter swapping row 1 and row 3:\n", A)

# A[[i, j]] → selects the two rows.

# Assigning them reversed → A[[j, i]] performs the swap in place.

Original array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

After swapping row 1 and row 3:
 [[ 0  1  2]
 [ 9 10 11]
 [ 6  7  8]
 [ 3  4  5]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [34]:
# Example: 10 triangles, each row = triplet of vertex indices
triangles = np.random.randint(0, 10, (10, 3))
print("Triangles:\n", triangles)

# Step 1: Extract edges from each triangle
# Each triangle has 3 edges (pairs of vertices)
edges = np.vstack([
    triangles[:, [0, 1]],
    triangles[:, [1, 2]],
    triangles[:, [2, 0]]
])

# Step 2: Sort each edge so (a, b) and (b, a) are treated the same
edges = np.sort(edges, axis=1)

# Step 3: Keep only unique edges
unique_edges = np.unique(edges, axis=0)

print("\nUnique edges (line segments):\n", unique_edges)

Triangles:
 [[1 3 5]
 [7 3 6]
 [6 7 9]
 [1 9 6]
 [0 3 8]
 [4 1 4]
 [5 0 3]
 [1 4 4]
 [4 0 0]
 [8 4 6]]

Unique edges (line segments):
 [[0 0]
 [0 3]
 [0 4]
 [0 5]
 [0 8]
 [1 3]
 [1 4]
 [1 5]
 [1 6]
 [1 9]
 [3 5]
 [3 6]
 [3 7]
 [3 8]
 [4 4]
 [4 6]
 [4 8]
 [6 7]
 [6 8]
 [6 9]
 [7 9]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [35]:
# Example bincount result
C = np.array([0, 2, 1, 0, 3])  
# Meaning: 0 appears 0 times, 1 appears 2 times, 2 appears 1 time, 3 appears 0 times, 4 appears 3 times

# Reconstruct A
A = np.repeat(np.arange(len(C)), C)

print("C =", C)
print("Reconstructed A =", A)
print("Check:", np.bincount(A), "==", C)

C = [0 2 1 0 3]
Reconstructed A = [1 1 2 4 4 4]
Check: [0 2 1 0 3] == [0 2 1 0 3]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [36]:
A = np.arange(10)   # [0 1 2 3 4 5 6 7 8 9]
k = 3               # window size

window = np.ones(k) / k
sliding_avg = np.convolve(A, window, mode='valid')

print(sliding_avg)

[1. 2. 3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [37]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(10)  # Example: [0 1 2 3 4 5 6 7 8 9]

# Window size = 3
M = sliding_window_view(Z, 3)

print(M)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [38]:
Z = np.array([True, False, True, False])

# Method 1: bitwise NOT (~) works in-place
Z = ~Z
print(Z)

# Method 2: XOR with True (also in-place)
Z ^= True
print(Z)

[False  True False  True]
[ True False  True False]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [41]:
# Example: 3 lines defined by start (P0) and end (P1) points
P0 = np.array([[0, 0],
               [1, 1],
               [2, 0]], dtype=float)

P1 = np.array([[1, 0],
               [2, 3],
               [3, 1]], dtype=float)

# Point p
p = np.array([1, 2], dtype=float)

# Vector from P0 to P1
dP = P1 - P0        # shape (n,2)

# Vector from P0 to p
dPp = p - P0        # shape (n,2)

# Cross product (2D -> scalar using determinant trick)
cross = np.abs(dP[:,0]*dPp[:,1] - dP[:,1]*dPp[:,0])

# Norm of direction vector
norms = np.linalg.norm(dP, axis=1)

# Distances
distances = cross / norms
print(distances)

[2.         0.4472136  2.12132034]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [43]:
def extract_centered(Z, shape, position, fill=0):
    """
    Extract a fixed-size subarray centered at a given position.
    Pads with `fill` if the window goes outside array bounds.

    Parameters
    ----------
    Z : np.ndarray
        Input array.
    shape : tuple of ints
        Desired shape of the subarray (e.g. (3,3)).
    position : tuple of ints
        Coordinates of the center element in Z.
    fill : scalar, optional
        Value to pad with (default=0).

    Returns
    -------
    subZ : np.ndarray
        Extracted subarray of shape `shape`.
    """
    shape = np.array(shape)
    position = np.array(position)
    dims = np.array(Z.shape)

    # half sizes
    half = shape // 2

    # output array initialized with fill
    out = np.full(shape, fill, dtype=Z.dtype)

    # coordinate ranges in input
    start_in = np.maximum(position - half, 0)
    end_in   = np.minimum(position + half + 1, dims)

    # coordinate ranges in output
    start_out = (start_in - (position - half))
    end_out   = start_out + (end_in - start_in)

    # copy from input to output
    out[tuple(map(slice, start_out, end_out))] = Z[tuple(map(slice, start_in, end_in))]

    return out


Z = np.arange(25).reshape(5,5)

# Extract a 3x3 patch centered at (0,0) with padding = -1
sub = extract_centered(Z, (3,3), (0,0), fill=-1)

print("Original:\n", Z)
print("\nPatch centered at (0,0):\n", sub)

Original:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Patch centered at (0,0):
 [[-1 -1 -1]
 [-1  0  1]
 [-1  5  6]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [44]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(1, 15)   # [1, 2, ..., 14]
R = sliding_window_view(Z, 4)

print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [45]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

rank = np.linalg.matrix_rank(A)

print("Matrix:\n", A)
print("Rank:", rank)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank: 2


#### 83. How to find the most frequent value in an array?

In [47]:
a = np.array([1, 2, 3, 2, 4, 2, 5, 1])
values, counts = np.unique(a, return_counts=True)
most_frequent = values[counts.argmax()]

print("Most frequent value:", most_frequent)

Most frequent value: 2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [48]:
# Random 10x10 matrix
Z = np.random.randint(0, 10, (10, 10))

# Extract contiguous 3x3 blocks
from numpy.lib.stride_tricks import sliding_window_view

blocks = sliding_window_view(Z, (3, 3))

print("Shape of blocks:", blocks.shape)   # (8, 8, 3, 3)
print("First block:\n", blocks[0, 0])

Shape of blocks: (8, 8, 3, 3)
First block:
 [[9 4 1]
 [6 2 3]
 [9 6 5]]


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [40]:
class SymmetricArray(np.ndarray):
"""A 2D square ndarray subclass that keeps itself symmetric: Z[i,j] == Z[j,i].


Behavior
--------
* Scalar assignments to single element pairs (Z[i,j] = v where i and j are ints)
are mirrored so both Z[i,j] and Z[j,i] get the same value.
* More complex assignments (slices, boolean masks, etc.) are allowed; after the
assignment the array is "symmetrized" by copying the upper triangle to the
lower triangle (so the upper triangle values take precedence).


Notes
-----
* The array must be 2-dimensional and square. Construction from non-square
data will raise a ValueError.
* The subclass preserves dtype and typical ndarray behavior.
"""


def __new__(cls, input_array, dtype=None, copy=False):
arr = np.array(input_array, dtype=dtype, copy=copy)
if arr.ndim != 2 or arr.shape[0] != arr.shape[1]:
raise ValueError("SymmetricArray must be created from a square 2D array")
obj = arr.view(cls)
return obj


def __array_finalize__(self, obj):
# Called on new view, slice, etc. Ensure shape validity and keep dtype
if obj is None:
return
if self.ndim != 2 or self.shape[0] != self.shape[1]:
raise ValueError("SymmetricArray must be 2D square")


def _symmetrize_upper_to_lower(self):
"""Make the array symmetric by copying upper triangle to lower triangle."""
# Work on a view; preserve dtype
n = self.shape[0]
iu = np.triu_indices(n, k=1)
# copy upper to lower
self[(iu[1], iu[0])] = self[iu]


def __setitem__(self, key, value):
# Handle scalar pair assignment (i, j) where i and j are integers
if (isinstance(key, tuple)
and len(key) == 2
and np.isscalar(key[0])
and np.isscalar(key[1])):
i, j = key
# convert to ints (allow numpy ints)
i = int(i); j = int(j)
super(SymmetricArray, self).__setitem__((i, j), value)
# Mirror to the symmetric position
super(SymmetricArray, self).__setitem__((j, i), value)
return


# Fallback: do the assignment, then symmetrize by copying upper->lower
super(SymmetricArray, self).__setitem__(key, value)
self._symmetrize_upper_to_lower()


# convenience constructor
@classmethod

IndentationError: expected an indented block after class definition on line 1 (79281964.py, line 2)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [39]:
p, n = 4, 3
M = np.random.randn(p, n, n)
V = np.random.randn(p, n, 1)

# Batch multiply and sum
result = np.einsum('pij,pjk->ik', M, V)

print(result.shape)  # (3,1)
print(result)

(3, 1)
[[-2.52232614]
 [ 0.01916465]
 [-1.08975204]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [24]:
Z = np.arange(16*16).reshape(16,16)

# Reshape into blocks: (4,4,4,4)
block_view = Z.reshape(4,4,4,4)

# Sum over last two axes
block_sum = block_view.sum(axis=(2,3))

print(block_sum)

[[ 120  376  632  888]
 [1144 1400 1656 1912]
 [2168 2424 2680 2936]
 [3192 3448 3704 3960]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [23]:
def game_of_life_step(X):
    """
    Perform one iteration of Conway's Game of Life.
    X: 2D NumPy array (0 = dead, 1 = alive)
    """
    # Count neighbors using convolution-like shifting
    neighbors = sum(np.roll(np.roll(X, i, 0), j, 1)
                    for i in (-1, 0, 1) for j in (-1, 0, 1)
                    if (i != 0 or j != 0))
    
    # Apply rules
    return (neighbors == 3) | ((X == 1) & (neighbors == 2))


# Example usage
np.random.seed(0)
X = np.random.randint(2, size=(6, 6))  # random 6x6 grid
print("Initial grid:\n", X.astype(int))

for step in range(3):   # run 3 steps
    X = game_of_life_step(X)
    print(f"\nStep {step+1}:\n", X.astype(int))

Initial grid:
 [[0 1 1 0 1 1]
 [1 1 1 1 1 0]
 [0 1 0 0 0 0]
 [0 1 0 1 1 0]
 [0 1 1 1 1 0]
 [1 0 1 0 1 1]]

Step 1:
 [[0 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [1 1 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

Step 2:
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 1 1]
 [1 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

Step 3:
 [[0 0 0 0 0 0]
 [0 0 0 0 0 1]
 [1 0 0 0 1 0]
 [1 0 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [22]:
arr = np.array([10, 2, 8, 4, 7, 15, 3])
n = 3

largest = np.sort(arr)[-n:]   # last n elements after sorting
print(largest)

[ 8 10 15]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [21]:
# Example: 3 vectors
A = np.array([1, 2])
B = np.array([3, 4])
C = np.array([5, 6])

# Build cartesian product
grid = np.array(np.meshgrid(A, B, C)).T.reshape(-1, 3)

print(grid)

[[1 3 5]
 [1 4 5]
 [2 3 5]
 [2 4 5]
 [1 3 6]
 [1 4 6]
 [2 3 6]
 [2 4 6]]


#### 91. How to create a record array from a regular array? (★★★)

In [19]:
# using arrays for columns

ids = [1, 2, 3]
vals = [2.5, 3.6, 4.7]
labels = ['foo', 'bar', 'baz']

r = np.rec.fromarrays([ids, vals, labels], names='id,value,label')

print(r)
print(r.id)




[(1, 2.5, 'foo') (2, 3.6, 'bar') (3, 4.7, 'baz')]
[1 2 3]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
Z = np.arange(1, 6) 

# Method 1: Using ** operator (vectorized)  
B1 = Z ** 3
print("Method 1:", B1)

# Method 2: Using np.power
B2 = np.power(Z, 3)
print("Method 2:", B2)

# Using elementwise multiplication
B3 = Z * Z * Z
print("Method 3:", B3)

4
Method 1: [  1   8  27  64 125]
Method 2: [  1   8  27  64 125]
Method 3: [  1   8  27  64 125]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [13]:
A = np.array([
    [1, 2, 3],
    [4, 1, 2],
    [5, 6, 7],
    [2, 3, 4],
    [8, 1, 4],
    [0, 2, 1],
    [9, 8, 7],
    [1, 4, 2]
])

B = np.array([
    [1, 2],
    [4, 8]
])

print("A:\n", A)
print("\nB:\n", B)

# For each row in B, check membership in A
results = []
for b in B:
    mask = np.all(np.isin(b, A), axis=0)  # ensure elements of b are in A (column-wise)
    # Better: check row-wise containment
    row_mask = np.array([np.all(np.isin(b, row)) for row in A])
    results.append(A[row_mask])

# Results per row in B
for i, rows in enumerate(results):
    print(f"\nRows of A containing elements {B[i]}:\n", rows)

A:
 [[1 2 3]
 [4 1 2]
 [5 6 7]
 [2 3 4]
 [8 1 4]
 [0 2 1]
 [9 8 7]
 [1 4 2]]

B:
 [[1 2]
 [4 8]]

Rows of A containing elements [1 2]:
 [[1 2 3]
 [4 1 2]
 [0 2 1]
 [1 4 2]]

Rows of A containing elements [4 8]:
 [[8 1 4]]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [12]:
X = np.random.randint(0, 5, (10, 3))
print("Original matrix:\n", X)

# Keep only rows with unequal values
m = np.any(X != X[:, [0]], axis=1)   # check if any value differs from the first in the row
filtered = X[m]

print("\nFiltered rows (with unequal values):\n", filtered)

Original matrix:
 [[1 3 3]
 [4 3 2]
 [1 1 0]
 [4 1 4]
 [2 1 4]
 [3 3 4]
 [3 3 1]
 [1 2 0]
 [2 2 1]
 [3 3 2]]

Filtered rows (with unequal values):
 [[1 3 3]
 [4 3 2]
 [1 1 0]
 [4 1 4]
 [2 1 4]
 [3 3 4]
 [3 3 1]
 [1 2 0]
 [2 2 1]
 [3 3 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [11]:
Z = np.array([1, 2, 3, 8, 15], dtype=np.uint8)

# Find number of bits needed (e.g., up to max value)
n_bits = int(np.ceil(np.log2(Z.max() + 1)))

# Convert each integer to binary representation
binary_matrix = ((Z[:, None] & (1 << np.arange(n_bits)[::-1])) > 0).astype(int)

print("Integers:", Z)
print("\nBinary matrix:\n", binary_matrix)

Integers: [ 1  2  3  8 15]

Binary matrix:
 [[0 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [1 0 0 0]
 [1 1 1 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [10]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9],
    [4, 5, 6]
])

print("Original array:\n", X)

# Extract unique rows
unique_rows = np.unique(X, axis=0)

print("\nUnique rows:\n", unique_rows)

Original array:
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]
 [4 5 6]]

Unique rows:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [9]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Inner Product
inner = np.einsum('i,i->', A, B)
print("Inner product:", inner)

# Outer Product
outer = np.einsum('i,j->ij', A, B)
print("Outer product:\n", outer)

# Sum of elements
s = np.einsum('i->', A)
print("Sum of A:", s)

# Elementwise Multiplication
mul = np.einsum('i,i->i', A, B)
print("Elementwise multiplication:", mul)

Inner product: 32
Outer product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Sum of A: 6
Elementwise multiplication: [ 4 10 18]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
def sample_path_equidistant(X, Y, m):
    """
    Sample the path defined by (X, Y) at m equidistant points along arc length.
    
    Parameters
    ----------
    X, Y : array_like, shape (N,)
        Coordinates of the path (N points).
    m : int
        Number of equidistant samples desired (>=2 recommended).
    
    Returns
    -------
    Xs, Ys : ndarray, shape (m,)
        Interpolated coordinates at equidistant arc-length positions.
    """
    X = np.asarray(X, dtype=float)
    Y = np.asarray(Y, dtype=float)
    if X.shape != Y.shape:
        raise ValueError("X and Y must have the same shape.")
    N = X.size
    if N == 0:
        return np.array([]), np.array([])

    # Compute segment lengths
    dx = np.diff(X)
    dy = np.diff(Y)
    seglen = np.hypot(dx, dy)  # sqrt(dx^2 + dy^2)
    cumlen = np.concatenate(([0.0], np.cumsum(seglen)))  # length along path, length N

    total = cumlen[-1]
    if total == 0:  # all points identical
        return np.full(m, X[0]), np.full(m, Y[0])

    # Remove zero-length segments (consecutive duplicate points) to ensure strictly increasing cumlen
    nonzero_mask = np.concatenate(([True], seglen > 1e-12))  # keep first point always
    cumlen_clean = cumlen[nonzero_mask]
    X_clean = X[nonzero_mask]
    Y_clean = Y[nonzero_mask]

    # If after cleaning we have only one point
    if cumlen_clean.size == 1:
        return np.full(m, X_clean[0]), np.full(m, Y_clean[0])

    # target equally spaced distances along the path (include endpoints)
    t = np.linspace(0.0, cumlen_clean[-1], m)

    # linear interpolation of X and Y versus cumulative length
    Xs = np.interp(t, cumlen_clean, X_clean)
    Ys = np.interp(t, cumlen_clean, Y_clean)
    return Xs, Ys

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [8]:
X = np.array([
    [2, 3, 5],
    [1.5, 4, 5],
    [4, 6, 0],
    [3, 2, 4]
])

n = 10  # total "degrees"

# Condition 1: all integers
is_integer = np.all(np.equal(np.mod(X, 1), 0), axis=1)

# Condition 2: row sums equal n
has_sum_n = np.sum(X, axis=1) == n

# Select valid rows
valid_rows = X[is_integer & has_sum_n]

print("Original X:\n", X)
print("\nValid multinomial rows (sum =", n, "):\n", valid_rows)

Original X:
 [[2.  3.  5. ]
 [1.5 4.  5. ]
 [4.  6.  0. ]
 [3.  2.  4. ]]

Valid multinomial rows (sum = 10 ):
 [[2. 3. 5.]
 [4. 6. 0.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [7]:
X = np.random.randn(100)  # 100 random values from standard normal

# Number of bootstrap resamples
N = 1000  

# Collect bootstrap means
means = []
for _ in range(N):
    sample = np.random.choice(X, size=len(X), replace=True)  # resample with replacement
    means.append(sample.mean())

means = np.array(means)

# Compute 95% confidence interval (2.5th and 97.5th percentiles)
ci_lower, ci_upper = np.percentile(means, [2.5, 97.5])

print("Original Mean:", X.mean())
print("Bootstrapped 95% CI:", (ci_lower, ci_upper))

Original Mean: 0.07784686941258759
Bootstrapped 95% CI: (np.float64(-0.09950440442683155), np.float64(0.26798698770514917))
