# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

2.3.3


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
a.size

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
b=np.zeros(10)
b[4]=1
print(b)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
c=np.random.randint(10,50)
print(c)

37


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
y=np.array([5,6,7,8,9])
z=y[: :-1]
print(z)

[9 8 7 6 5]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
b=np.random.randint(0,8,size=(3,3))
print(b)

[[7 6 1]
 [2 1 7]
 [0 4 3]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
p=r=np.array([1,2,0,0,4,0])
t=np.nonzero(p)
print(t)


(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [16]:
u=np.identity(3)
print(u)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [26]:
s=np.random.random((3,3,3))
print(s)

[[[0.57908152 0.84614661 0.62906761]
  [0.34405739 0.99555067 0.65694326]
  [0.48843553 0.16558183 0.71893893]]

 [[0.03789452 0.53847707 0.88179034]
  [0.88609463 0.96839622 0.29970295]
  [0.34322099 0.03034579 0.01457752]]

 [[0.87929975 0.59216964 0.34202445]
  [0.01466678 0.11926358 0.37550605]
  [0.62229767 0.30025707 0.79548823]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [22]:
z=np.random.random((10,10))
print(z)
minimum_value=np.min(z)
print(f'The minimum value is {minimum_value}')
maximum_value=np.max(z)
print(f'The maximum value is {maximum_value}')


[[0.91859875 0.08584216 0.36315664 0.0233379  0.68159255 0.90243359
  0.57946614 0.73030859 0.86337439 0.97437469]
 [0.71670059 0.96836822 0.6429968  0.97160181 0.26124041 0.13552008
  0.30748388 0.72591583 0.44746557 0.72696771]
 [0.54969691 0.70902303 0.71662351 0.34984266 0.564651   0.48534588
  0.46281602 0.71040943 0.12112791 0.85725139]
 [0.36325305 0.46167184 0.29251766 0.91538635 0.1459823  0.14785754
  0.16777499 0.4777682  0.47146147 0.95045832]
 [0.9496196  0.13308979 0.60036622 0.94169745 0.62703122 0.71658247
  0.07853879 0.49521182 0.4093486  0.53073222]
 [0.3715608  0.83448692 0.63507356 0.73867185 0.14970803 0.17549262
  0.61629623 0.88246395 0.92552361 0.65066684]
 [0.09955425 0.85149438 0.84822782 0.05190163 0.83739017 0.91273605
  0.72044484 0.10418326 0.75228804 0.47041408]
 [0.54285197 0.5445843  0.08661342 0.0267023  0.44995885 0.79320133
  0.0991257  0.51863485 0.99479557 0.09329291]
 [0.83536003 0.71886802 0.61247924 0.83428133 0.55538194 0.80390485
  0.90643892

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [27]:
y=np.random.random(30)
print(y)
w=np.mean(y)
print(f'The mean is {w}')

[0.57559028 0.13433387 0.28037404 0.79181927 0.6547369  0.66402828
 0.45406169 0.1189636  0.75882826 0.81348226 0.79432811 0.27753097
 0.7414723  0.71351479 0.94397665 0.05841527 0.14484097 0.80784047
 0.70754177 0.44431617 0.39154223 0.04953897 0.86101919 0.94204455
 0.99216872 0.87508906 0.65442274 0.59674967 0.57559703 0.32635963]
The mean is 0.5714842569911092


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [42]:
v=np.ones((5,5))
print(v)
x=np.zeros((3,3))
print(x)

v[1:4,1:4]=x
print(v)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
