# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan                             
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [6]:

b=np.zeros((5,5))
print(b)

numbers= [1, 2, 3, 4]

c=np.diag(numbers,k=-1)
print(c)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [10]:
d=np.ones((8,8))
d
d[1::2, ::2] = 0   # rows 1,3,5,7 → cols 0,2,4,6
d[::2, 1::2] = 0  # rows 0,2,4,6 → cols 1,3,5,7

print(d)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [12]:
pattern = np.array([[0, 1],
                    [1, 0]])


x = np.tile(pattern, (4, 4))

print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
y = np.random.random((5,5)) 
print("Original matrix:\n", y)

Original matrix:
 [[0.94149774 0.12269856 0.50997757 0.55780157 0.9717509 ]
 [0.8360856  0.24113517 0.68850021 0.06533434 0.32051658]
 [0.14406591 0.63543234 0.60448926 0.43275325 0.46458587]
 [0.96597859 0.44312033 0.94489891 0.47273154 0.33421326]
 [0.30136533 0.9382792  0.66963991 0.03015672 0.06196209]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [22]:
A = np.random.rand(5, 3)

B = np.random.rand(3, 2)


C = np.dot(A, B)     # or A @ B

print("A shape:", A.shape)
print("B shape:", B.shape)
print("C shape:", C.shape)
print(C)

A shape: (5, 3)
B shape: (3, 2)
C shape: (5, 2)
[[0.60797505 0.27343734]
 [1.24605157 1.04753926]
 [0.85891899 0.65091881]
 [0.47330232 0.24974637]
 [1.18154016 0.82519406]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [24]:
T = np.arange(11)   
print("Before:", T)


T[(T >= 3) & (T<= 8)] *= -1

print("After:", T)

Before: [ 0  1  2  3  4  5  6  7  8  9 10]
After: [ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [25]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Legal: Z**Z, 2 << Z >> 2, 1j*Z, Z/1/1

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.float64(nan)
np.int64(0)
array([-9.22337204e+18])


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
a = np.array([-1.3, -1.7, 1.3, 1.7, 0.2, -0.2])

m = np.sign(a) * np.ceil(np.abs(a))
print(m)

# np.abs(a) → makes everything positive

# np.ceil(...) → rounds up to the next integer

# np.sign(a) → restores the original sign

# multiply → gives the rounded value away from zero

[-2. -2.  2.  2.  1. -1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [16]:
a = np.array([1, 2, 3, 8, 10])
b = np.array([8, 10, 6, 7, 4])

common = np.intersect1d(a, b)
print(common)

[ 8 10]
